DROP TABLE IF EXISTS "ProductinCells" CASCADE;
DROP TABLE IF EXISTS "ProductInOrder" CASCADE;
DROP TABLE IF EXISTS "Reserve" CASCADE;
DROP TABLE IF EXISTS "OrderHistory" CASCADE;
DROP TABLE IF EXISTS "Order" CASCADE;
DROP TABLE IF EXISTS "Product" CASCADE;
DROP TABLE IF EXISTS "StorageCell" CASCADE;
DROP TABLE IF EXISTS "OrderStatus" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
DROP TABLE IF EXISTS "Role" CASCADE;
DROP TABLE IF EXISTS "Info" CASCADE;

DROP FUNCTION IF EXISTS update_timestamp();