server {
  listen 8080 default;
  root /usr/share/nginx/html/;

  location / {
    try_files $uri @index;
  }

  location ~ \.(js|mjs|css) {
    try_files $uri =404;
  }

  location @index {
    add_header Cache-Control "no-cache, no-store, must-revalidate";
    expires off;
    try_files /index.html =404;
  }
}
