services:
  postgres:
    container_name: postgres-db
    image: postgres:latest
    expose:
      - "5432"
    networks:
      - my-network
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_DB: dbname
    ports:
      - '5432:5432'
    volumes:
      - ./backend/postgres-data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: frontend-dev
    networks:
      - my-network
    ports:
      - "80:80"
      - "8080:8080"
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    container_name: backend-dev
    networks:
      - my-network
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:example@postgres:5432/dbname?schema=public
    volumes:
      - ./backend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge
